[package]
name = "risc-powdr"
version = "0.1.0"
edition = "2021"


[dependencies]
clap = { version = "4.1.8", features = ["derive"] }
lalrpop = "0.19.8"
lalrpop-util = "0.19.8"
mktemp = "0.5.0"

[build-dependencies]
lalrpop = "0.19.8"
